FROM mcr.microsoft.com/dotnet/sdk:6.0

# install dotnet tool
ENV PATH $PATH:/root/.dotnet/tools

WORKDIR /source
COPY . .

RUN chmod +x ./InstallDotnetTools.sh
RUN ./InstallDotnetTools.sh

# copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore --use-current-runtime  

# copy everything else and build app
COPY . .
RUN dotnet publish -c Release -o /app

WORKDIR /app
ENTRYPOINT ["dotnet", "AspNetCoreDemo.dll"]