FROM mcr.microsoft.com/dotnet/sdk:6.0

# copy csproj and restore as distinct layers
WORKDIR /source
COPY *.csproj .
RUN dotnet restore --use-current-runtime  

# install dotnet tool
ENV PATH $PATH:/root/.dotnet/tools
COPY . .
RUN chmod +x ./InstallDotnetTools.sh
RUN ./InstallDotnetTools.sh

# copy everything else and build app
RUN dotnet publish -c Release -o /app

EXPOSE 80
WORKDIR /app
ENTRYPOINT ["dotnet", "AspNetCoreDemo.dll"]